# Generated by Django 3.2.4 on 2021-08-10 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='artice',
            new_name='article',
        ),
    ]
